services:
  app:
    build:
      context: .
    container_name: django_app
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DEBUG: "True"
      SECRET_KEY: your_secret_key
      DATABASE_URL: sqlite:///db.sqlite3
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis
    stdin_open: true
    tty: true

  redis:
    image: redis:7
    container_name: redis_service
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    container_name: celery_worker
    command: poetry run celery -A core worker --loglevel=info
    environment:
      DEBUG: "True"
      SECRET_KEY: "django-insecure-(g5o349%pxyl=-x81&lk32v4c-^b)i&oe)fp!*g_muzve1ec_j"
      DATABASE_URL: sqlite:///db.sqlite3
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis
      - app
    volumes:
      - .:/app

  celery_beat:
    build:
      context: .
    container_name: celery_beat
    command: poetry run celery -A core beat --loglevel=info
    environment:
      DEBUG: "True"
      SECRET_KEY: "django-insecure-(g5o349%pxyl=-x81&lk32v4c-^b)i&oe)fp!*g_muzve1ec_j"
      DATABASE_URL: sqlite:///db.sqlite3
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis
      - app
    volumes:
      - .:/app