# Generated by Django 5.1.3 on 2024-11-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelquestion',
            name='exam',
        ),
        migrations.AddField(
            model_name='modelquestion',
            name='exam',
            field=models.ManyToManyField(related_name='questions', to='api.modelexam'),
        ),
    ]
